-- MySQL Script generated by MySQL Workbench
-- Wed 03 Jun 2015 01:25:34 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema web_course
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema web_course
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `web_course` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `web_course` ;

-- -----------------------------------------------------
-- Table `web_course`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL COMMENT '用户名',
  `password` VARCHAR(128) NOT NULL COMMENT '用户密码',
  `nick_name` VARCHAR(45) NULL,
  `create_time` VARCHAR(45) NULL COMMENT '用户创建时间',
  `update_time` VARCHAR(45) NULL COMMENT '用户信息更新时间',
  `path_head_picture` VARCHAR(64) NULL COMMENT '用户头像照片存储路径',
  `me_info` TEXT NULL COMMENT '用户一些个人的宣言等等  如果需要什么其他的，后期可转为json存储，所以我用的text文本存储',
  `telephone` VARCHAR(45) NULL COMMENT '用户电话号码',
  `mailbox` VARCHAR(45) NULL COMMENT '用户邮箱',
  `last_login_time` VARCHAR(45) NULL COMMENT '用户最后一次登录时间',
  `num_star` INT(11) NULL DEFAULT 0 COMMENT '用户星级，最大值10，最小值0，五颗星星，没增大一，星星多亮半颗',
  `school_name` VARCHAR(45) NULL COMMENT '用户学校',
  `school_card` VARCHAR(45) NULL COMMENT '用户校园卡号',
  `birth_date` VARCHAR(45) NULL COMMENT '用户出生日期',
  `qq` VARCHAR(45) NULL COMMENT '用户qq号',
  `weixin` VARCHAR(45) NULL COMMENT '用户微信号',
   UNIQUE KEY (`id`),
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户类, 关于管理者，可以在用户登录界面中直接判断'
PACK_KEYS = DEFAULT PARTITION BY KEY() PARTITIONS 1 ;


-- -----------------------------------------------------
-- Table `web_course`.`Activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Activities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '活动id自增长',
  `name` VARCHAR(45) NOT NULL COMMENT '活动的名字',
  `content` LONGTEXT NOT NULL COMMENT '活动的内容',
  `start_time` VARCHAR(45) NOT NULL COMMENT '活动开始的时间',
  `end_time` VARCHAR(45) NULL COMMENT '活动结束后的时间',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_danish_ci
COMMENT = '活动表'
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `web_course`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Role` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `describe` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '定义每个角色，所持有的操作，以及角色和角色的继承关系。查表时，提供每个角色能执行的所有操作的权限';


-- -----------------------------------------------------
-- Table `web_course`.`Teamer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Teamer` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
  `name` VARCHAR(64) NOT NULL COMMENT '队标名字',
  `info` TEXT NULL COMMENT '队伍详情',
  `create_time` VARCHAR(45) NOT NULL COMMENT '队伍创建时间',
  `path_logo` VARCHAR(45) NULL COMMENT '队伍图标路径',
  `activity_id` INT(11) NOT NULL COMMENT '引用Activities表的活动id，从而知道每个队伍属于哪个活动',
  `typee` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_idx` (`activity_id` ASC),
  CONSTRAINT `id`
    FOREIGN KEY (`activity_id`)
    REFERENCES `web_course`.`Activities` (`id`)
        ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `web_course`.`Team_user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Team_user_role` (
  `team_id` INT(11) NOT NULL COMMENT '用户id,来自Users',
  `user_id` INT(11) NOT NULL COMMENT '队伍id，引用Teamer',
  `role` INT(11) NOT NULL COMMENT '用户角色，引用AuthItemChild',
  PRIMARY KEY (`team_id`, `user_id`, `role`),
  INDEX `id_idx` (`user_id` ASC),
  INDEX `parent_idx` (`role` ASC),
  CONSTRAINT `role_id`
    FOREIGN KEY (`role`)
    REFERENCES `web_course`.`Role` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `teamer_id`
    FOREIGN KEY (`team_id`)
    REFERENCES `web_course`.`Teamer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '第一个队伍中，一个人，所承担的角色，或者一个角色所继承的角色，存储权限的数据库';


-- -----------------------------------------------------
-- Table `web_course`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Admin` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '登录界面用于，匹配是否是管理员的操作，管理员拥有无限权限';


-- -----------------------------------------------------
-- Table `web_course`.`Comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`Comment` (
  `user_id` INT(11) NOT NULL COMMENT '用户id，引用Users表中的id字段',
  `team_id` INT(11) NOT NULL COMMENT '队伍id，引用Teamer表中的id字段',
  `content` TEXT NOT NULL COMMENT '用户在一个队伍中的评论',
  `push_time` VARCHAR(45) NOT NULL COMMENT '评论发布的时间',
  INDEX `id_idx` (`user_id` ASC),
  INDEX `id_idx1` (`team_id` ASC),
  PRIMARY KEY (`team_id`, `user_id`),
  CONSTRAINT `id111`
    FOREIGN KEY (`user_id`)
    REFERENCES `web_course`.`Users` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `id222`
    FOREIGN KEY (`team_id`)
    REFERENCES `web_course`.`Teamer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = '用户评论'
PACK_KEYS = DEFAULT;

USE `web_course` ;

-- -----------------------------------------------------
-- Placeholder table for view `web_course`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`view1` (`id` INT);

-- -----------------------------------------------------
-- Placeholder table for view `web_course`.`view2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `web_course`.`view2` (`id` INT);

-- -----------------------------------------------------
-- View `web_course`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_course`.`view1`;
USE `web_course`;


-- -----------------------------------------------------
-- View `web_course`.`view2`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `web_course`.`view2`;
USE `web_course`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
